# Generated by Django 4.2.3 on 2023-07-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0002_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('COUPE/SPORT', 'Coupe/Sport'), ('HATCHBACK', 'Hatchback'), ('SUV', 'SUV/4x4'), ('VAN', 'Van'), ('SEDAN', 'Sedan')], default='HATCHBACK', max_length=12),
        ),
    ]
